% NBPSO code v1.0
% Generated by Majid Rostami Shahrbabaki, 2010. 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%5
% Particle swarm optimization (PSO) is one of the modern heuristic algorithms that can be applied to continuous and discrete optimization problems.
% The original binary PSO (BPSO) has got some disadvantages that make the algorithm not to converge well.
% To deal with these disadvantages, a new BPSO (NBPSO) is introduced. The results provided in the following papers show the superiority of the NBPSO.
% 
% [1]. M.Rostami Shahrbabak and H.Nezamabadi-pour, " A New Approach to Binary PSO Algorithm" 14th Iranian Conference on Electrical Engineering, may 2006.
% [2]. H.Nezamabadi-pour, M.Rostami Shahrbabaki and M.Maghfoori Farsangi "Binary Particle Swarm Optimization: Challenges and new
% Solutions"The CSI Journal on Computer Science and Engineering Vol. 6, No. 1 (a), pp. 21-32, 2008.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Main function for NBPSO algorithm. The function called here are :
% initialize : gives the initial parameters
% range_func : depend on the Num_func, determines ranges for position and velocity
% evaluate : depend on the Num_func, evaluates the function
% renewp_best : finds the Particle_best
% renewg_best : finds the Global_best
% update_v_p  : updates position and velocities of particles
% display_result : displays the results

%clear,close all,clc  %#ok<DUALC>

function [fitness]=PSO_main(iteration_count, particle_count)

close all

[y, fs] = wavread('audio2.wav');
duration = size(y,1)/fs;

%read in the given tags to do a comparison
giventags = dlmread('audio2.tag');

%
% BEST AUDIO1 RESULT
% individual1.of= 5;
% individual1.pr=0.7;  
% individual1.ts= 0.101009157193833; 
% individual1.tn= 0.039162892507541;
% individual1.ti= 0.097479128621034;   
% individual1.ri=0;       
% individual1.ta=0.396;    
% individual1.gx=8.222561384385975e+02;
% individual1.xn=1.112044017661430;
% 
% tags1 = vadsohn(y, fs, 'a', individual1);
% vadOptimality(tags1, giventags, duration, 0)
%
%  BEST AUDIO2 RESULT (but not actually because format long as off :( )
% individual3.of= 1;
% individual3.pr=0.7;  
% individual3.ts= 1.5515; 
% individual3.tn= 0.0017;
% individual3.ti= 0.0352;   
% individual3.ri=0;       
% individual3.ta=0.396;    
% individual3.gx=28.5170;
% individual3.xn=0.6902;
% 
% tags3 = vadsohn(y, fs, 'a', individual3);
% vadOptimality2(tags3, giventags)

figh = figure;
plotenable = 0;
tic
if (nargin == 0)
    jmax = 20;
else
    jmax = 20;
end
for j = 1:jmax
    min_fitness = 10^10;
    min_individual = 0;
    count = 0;
    if (nargin > 0)
        K = iteration_count;
        if (nargin > 1)
            N = particle_count;
        else
            N = K;
        end
    else
        N = 20; % N is the number of the particles
        K = 50; %K is the number of iteration
    end
    [D,L,var,w_max,w_min,c1,c2,position,p_best,g_best,fitness,p_best_fit,...
        Num_func,Min_Max_flag,Gl_Lo_flag] = PSO_initialize(N,K);

    [v_max,x_max,velocity,] = PSO_range_func(Num_func,N,D) ;
    for k=1:(10*K)
        %disp([' Run ' , num2str(k) ])
        w = w_max+(((w_min-w_max)*(k-1))/(min(K, 50)-1));
        iteration = k;
        [fitness, min_fitness, min_individual, count] = ...
            PSO_evaluate(position, k, N, D, L, var, x_max, fitness, y, ...
                         fs, duration, giventags, Num_func, min_fitness, ...
                         min_individual, count, plotenable, figh, iteration);
        if count == 50
            disp(['done at ', num2str(k - 50), ' iterations ' ])
            disp(['fitness at ', num2str(k - 50), ': ', num2str(min_fitness) ])
            break;
        end
        if k == 50
            disp(['fitness at 50: ', num2str(min_fitness) ])
        end
        [p_best,p_best_fit] = PSO_renewp_best(D,fitness,p_best,N,k,position,p_best_fit,Min_Max_flag);
        g_best=PSO_renewg_best(p_best,p_best_fit,N,Min_Max_flag,Gl_Lo_flag);
        [position,velocity]=PSO_update_v_p(D,N,c1,c2,w,p_best,g_best,position,velocity,v_max,Gl_Lo_flag);
    end
    if (nargin == 0)
        if Min_Max_flag == 1
            best_fit(j,:) = min(fitness);   %#ok<SAGROW> 
        else
            best_fit(j,:) = min(fitness); %#ok<SAGROW>
        end
        mean_fit(j,:) = mean(fitness); %#ok<SAGROW>
    end
    %min_fitness
    %min_individual
end
toc
if (nargin == 0)
    PSO_display_result(best_fit,mean_fit,K,Min_Max_flag)
end
end



